/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ifnmg.ds.frontend;

/**
 *
 * @author leonardosilva
 */
public class FrmDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FrmDashboard
     */
    public FrmDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBody = new javax.swing.JPanel();
        pnlPlayers = new javax.swing.JPanel();
        lblPlayer1 = new javax.swing.JLabel();
        lblPlayer2 = new javax.swing.JLabel();
        cbbPlayers = new javax.swing.JComboBox<>();
        pnlSkills = new javax.swing.JPanel();
        lblSpeedPlayer1 = new javax.swing.JLabel();
        lblManueverabilityPlayer1 = new javax.swing.JLabel();
        lblPowerPlayer1 = new javax.swing.JLabel();
        pnlSkills1 = new javax.swing.JPanel();
        lblSpeedPlayer2 = new javax.swing.JLabel();
        lblManueverabilityPlayer2 = new javax.swing.JLabel();
        lblPowerPlayer2 = new javax.swing.JLabel();
        tfPlayer2 = new javax.swing.JTextField();
        lblLane22 = new javax.swing.JLabel();
        lblImgPlayer01 = new javax.swing.JLabel();
        lblLane12 = new javax.swing.JLabel();
        lblLane52 = new javax.swing.JLabel();
        lblLane33 = new javax.swing.JLabel();
        lblLane43 = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        btnRollDice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mario Kart Simulator");
        setResizable(false);

        pnlBody.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlPlayers.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblPlayer1.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPlayer1.setText("Player 1 - YOU");
        lblPlayer1.setAlignmentY(0.0F);
        lblPlayer1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPlayer2.setFont(new java.awt.Font("Rockwell", 0, 16)); // NOI18N
        lblPlayer2.setText("Player 2 - Computer");

        cbbPlayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mario", "Bowser", "Toad", "Luighi" }));

        pnlSkills.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblSpeedPlayer1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblSpeedPlayer1.setText("Speed: 5");

        lblManueverabilityPlayer1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblManueverabilityPlayer1.setText("Manueverability: 2");

        lblPowerPlayer1.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblPowerPlayer1.setText("Power: 5");

        javax.swing.GroupLayout pnlSkillsLayout = new javax.swing.GroupLayout(pnlSkills);
        pnlSkills.setLayout(pnlSkillsLayout);
        pnlSkillsLayout.setHorizontalGroup(
            pnlSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpeedPlayer1)
                    .addComponent(lblManueverabilityPlayer1)
                    .addComponent(lblPowerPlayer1))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlSkillsLayout.setVerticalGroup(
            pnlSkillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkillsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSpeedPlayer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblManueverabilityPlayer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPowerPlayer1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlSkills1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblSpeedPlayer2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblSpeedPlayer2.setText("Speed: 4");

        lblManueverabilityPlayer2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblManueverabilityPlayer2.setText("Manueverability: 3");

        lblPowerPlayer2.setFont(new java.awt.Font("Helvetica Neue", 0, 15)); // NOI18N
        lblPowerPlayer2.setText("Power: 3");

        javax.swing.GroupLayout pnlSkills1Layout = new javax.swing.GroupLayout(pnlSkills1);
        pnlSkills1.setLayout(pnlSkills1Layout);
        pnlSkills1Layout.setHorizontalGroup(
            pnlSkills1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkills1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSkills1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSpeedPlayer2)
                    .addComponent(lblManueverabilityPlayer2)
                    .addComponent(lblPowerPlayer2))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlSkills1Layout.setVerticalGroup(
            pnlSkills1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSkills1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSpeedPlayer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblManueverabilityPlayer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPowerPlayer2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tfPlayer2.setText("Bowser");
        tfPlayer2.setEnabled(false);

        javax.swing.GroupLayout pnlPlayersLayout = new javax.swing.GroupLayout(pnlPlayers);
        pnlPlayers.setLayout(pnlPlayersLayout);
        pnlPlayersLayout.setHorizontalGroup(
            pnlPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayersLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlayersLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(pnlPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayer2)
                    .addComponent(pnlSkills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPlayersLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(tfPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(pnlPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPlayersLayout.createSequentialGroup()
                    .addContainerGap(26, Short.MAX_VALUE)
                    .addComponent(pnlSkills1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );
        pnlPlayersLayout.setVerticalGroup(
            pnlPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlayersLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191)
                .addComponent(lblPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(tfPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlSkills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(pnlPlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPlayersLayout.createSequentialGroup()
                    .addGap(123, 123, 123)
                    .addComponent(pnlSkills1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(307, Short.MAX_VALUE)))
        );

        lblLane22.setFont(new java.awt.Font("Liberation Sans", 0, 59)); // NOI18N
        lblLane22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLane22.setText("2");
        lblLane22.setMaximumSize(new java.awt.Dimension(151, 151));
        lblLane22.setMinimumSize(new java.awt.Dimension(151, 151));
        lblLane22.setPreferredSize(new java.awt.Dimension(151, 151));

        lblImgPlayer01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImgPlayer01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mario-face.png"))); // NOI18N
        lblImgPlayer01.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblLane12.setBackground(new java.awt.Color(51, 0, 51));
        lblLane12.setFont(new java.awt.Font("Liberation Sans", 0, 59)); // NOI18N
        lblLane12.setForeground(new java.awt.Color(255, 255, 255));
        lblLane12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLane12.setText("1");
        lblLane12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLane12.setOpaque(true);

        lblLane52.setBackground(new java.awt.Color(51, 0, 51));
        lblLane52.setFont(new java.awt.Font("Liberation Sans", 0, 59)); // NOI18N
        lblLane52.setForeground(new java.awt.Color(255, 255, 255));
        lblLane52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLane52.setText("5");
        lblLane52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblLane52.setMaximumSize(new java.awt.Dimension(151, 151));
        lblLane52.setMinimumSize(new java.awt.Dimension(151, 151));
        lblLane52.setOpaque(true);
        lblLane52.setPreferredSize(new java.awt.Dimension(151, 151));

        lblLane33.setBackground(new java.awt.Color(51, 0, 51));
        lblLane33.setFont(new java.awt.Font("Liberation Sans", 0, 59)); // NOI18N
        lblLane33.setForeground(new java.awt.Color(255, 255, 255));
        lblLane33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLane33.setText("3");
        lblLane33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblLane33.setMaximumSize(new java.awt.Dimension(151, 151));
        lblLane33.setMinimumSize(new java.awt.Dimension(151, 151));
        lblLane33.setOpaque(true);
        lblLane33.setPreferredSize(new java.awt.Dimension(151, 151));

        lblLane43.setFont(new java.awt.Font("Liberation Sans", 0, 59)); // NOI18N
        lblLane43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLane43.setText("4");
        lblLane43.setMaximumSize(new java.awt.Dimension(151, 151));
        lblLane43.setMinimumSize(new java.awt.Dimension(151, 151));
        lblLane43.setPreferredSize(new java.awt.Dimension(151, 151));

        javax.swing.GroupLayout pnlBodyLayout = new javax.swing.GroupLayout(pnlBody);
        pnlBody.setLayout(pnlBodyLayout);
        pnlBodyLayout.setHorizontalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBodyLayout.createSequentialGroup()
                .addComponent(pnlPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImgPlayer01)
                    .addGroup(pnlBodyLayout.createSequentialGroup()
                        .addComponent(lblLane12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblLane33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(lblLane43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLane52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 193, Short.MAX_VALUE))
        );
        pnlBodyLayout.setVerticalGroup(
            pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                .addComponent(pnlPlayers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblImgPlayer01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLane52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLane33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLane43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLane12)
                        .addComponent(lblLane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92))
        );

        getContentPane().add(pnlBody, java.awt.BorderLayout.PAGE_END);

        btnStart.setBackground(new java.awt.Color(102, 102, 255));
        btnStart.setFont(new java.awt.Font("Menlo", 1, 25)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("START");
        btnStart.setAlignmentY(0.0F);
        btnStart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnRollDice.setBackground(new java.awt.Color(204, 204, 204));
        btnRollDice.setFont(new java.awt.Font("Menlo", 1, 20)); // NOI18N
        btnRollDice.setForeground(new java.awt.Color(255, 255, 255));
        btnRollDice.setText("Roll Dice!");
        btnRollDice.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnRollDice, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267)
                .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(592, Short.MAX_VALUE))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRollDice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRollDice;
    private javax.swing.JButton btnStart;
    private javax.swing.JComboBox<String> cbbPlayers;
    private javax.swing.JLabel lblImgPlayer01;
    private javax.swing.JLabel lblLane12;
    private javax.swing.JLabel lblLane22;
    private javax.swing.JLabel lblLane33;
    private javax.swing.JLabel lblLane43;
    private javax.swing.JLabel lblLane52;
    private javax.swing.JLabel lblManueverabilityPlayer1;
    private javax.swing.JLabel lblManueverabilityPlayer2;
    private javax.swing.JLabel lblPlayer1;
    private javax.swing.JLabel lblPlayer2;
    private javax.swing.JLabel lblPowerPlayer1;
    private javax.swing.JLabel lblPowerPlayer2;
    private javax.swing.JLabel lblSpeedPlayer1;
    private javax.swing.JLabel lblSpeedPlayer2;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlPlayers;
    private javax.swing.JPanel pnlSkills;
    private javax.swing.JPanel pnlSkills1;
    private javax.swing.JTextField tfPlayer2;
    // End of variables declaration//GEN-END:variables
}
